### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ThisIsABug** [aureliendavid/rsspreview#35]
Is there somewhere some custom css code for a dark theme regarding the rss-viewer?

**Comment by DarylSun** [comment]
I'm kinda rusty with my CSS skills, but I managed to whip up a black theme for the RSS preview page.

```
html {color: white; background-color: black;}
img {opacity:1; filter: invert(100%);}
#feedBody {background-color: black;}
#rsspreviewBody {background-color: black;}
.enclosures {background-color: black;}
```

**Comment by aureliendavid** [comment]
That's good, thanks! It works well as a high-contrast theme. 

Here's a quick attempt to adapt it to a dark, gray-ish theme : 

```css
html {color: #bbbbbb; background-color: black;}
#feedBody {background-color: #1e1e1e;}
#rsspreviewBody {background-color: #0e0e0e;}
.enclosures {background-color: #2e2e2e;}
a { color: #8FC2EF; }
a:visited { color: #DFC2EF; }
```
