### ISSUE TITLE
custom CSS doesn't work on lore.kernel.org feeds

### ISSUE THREAD

**Issue by marlop352** [aureliendavid/rsspreview#69]
Custom CSS doesn't cause any change on the feeds on https://lore.kernel.org, example: https://lore.kernel.org/lkml/new.atom .
Doesn't seem to fail on all atom feeds as this: https://github.com/aureliendavid/rsspreview/releases.atom works fine.

I'm using this CSS: 
```CSS
html {color: #bbbbbb; background-color: black !important;}
#feedBody {background-color: #1e1e1e;}
.enclosures {background-color: #2e2e2e;}
a {color: #8FC2EF;}
a:visited {color: #DFC2EF;}
```
adapted from: https://github.com/aureliendavid/rsspreview/issues/35#issuecomment-504349484

Tested on a clean profile to make sure it wasn't interference from any other add-on or Firefox config option.

Sysinfo:
Windows 11
Firefox 95.0.2 x64
