### ISSUE TITLE
Custom CSS does not apply to kernel.org main page feeds, regardless of bypass CSP preference

### ISSUE THREAD

**Issue by mmkthecoolest** [aureliendavid/rsspreview#84]
Feeds used in the main [Linux kernel site](https://kernel.org) do not use the custom CSS with the extension (examples: https://www.kernel.org/feeds/all.atom.xml and https://www.kernel.org/feeds/kdist.xml), regardless of the bypass CSP setting. I double checked with #69 and [lore.kernel.org](https://lore.kernel.org/lkml/new.atom) still works.

Custom CSS to test with
```CSS
#feedBody {
 max-width: 1100px;
 border: 0px;
 border-radius: 10px;
}
body {
 font-family: sans-serif;
}
video {
 max-width: 100%;
 border-radius: 5px;
}
img {
 border-radius: 5px;
}
.enclosures {
 border: 0px;
 border-radius: 5px;
}
h1 {
 font-size: 200%;
 border-bottom: 0px;
}
@media (prefers-color-scheme: dark){
  #feedBody {
   background-color: #222222;
  }
  
  #rsspreviewBody {
  background-color: black;
  
  }
  h2, #feedLastUpdate {
   color: #aaaaaa;
  }
  a {
   color: #aaaaff;
  }
  
  a:active {
   color: #ff5555;
  }
  .enclosures {
   background-color: #333333;
  }
  html {
   color: #eeeeee;
   background-color: black;
  }
}
```
